name: Build

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - .gitignore
      - "*.bat"
      - "assets/**"
      - appveyor.yml
      - CHANGELOG*
      - LICENSE*
      - README*
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      # Set up committer info and GPG key
      - name: Import GPG key
        id: import_gpg
        if: github.event.pull_request.merged == true && github.event.pull_request.branch == "master"
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          git-commit-gpgsign: true
          git-committer-email: "${{ secrets.XLABS_CI_EMAIL }}"
          git-committer-name: "${{ secrets.XLABS_CI_NAME }}"
          git-push-gpgsign: true
          git-tag-gpgsign: true
          git-user-signingkey: true
          gpg-private-key: ${{ secrets.XLABS_CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.XLABS_CI_GPG_PASSPHRASE }}

      - name: Extract version from changelog
        id: changelog_reader
        if: github.event.pull_request.merged == true && github.event.pull_request.branch == master
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 2
          path: ./CHANGELOG.md

      - name: Create annotated tag
        if: github.event.pull_request.merged == true && github.event.pull_request.branch == master
        run: |
          git tag -a -m "${{ steps.changelog_reader.outputs.changes }}" \
            "${{ steps.changelog_reader.outputs.version }}" \
            "${{ github.event.pull_request.merge_commit_sha }}"
          git push origin --tags

      - name: Check out files
        uses: actions/checkout@v2
        with:
          submodules: true
          # NOTE - if LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate project files
        run: tools/premake5 vs2019

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/iw6x.sln

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/**/*.exe
            build/bin/**/*.dll

      - name: Upload ${{matrix.configuration}} debug symbols
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} debug symbols
          path: |
            build/bin/**/*.pdb

      - name: Post CI status notification to Discord
        uses: sarisia/actions-status-discord@v1.7.1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_CI_BOT_WEBHOOK }}
          title: "${{matrix.configuration}} Build"

  release:
    name: Tag new version
    needs: build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.branch == master
    steps:
      # Set up committer info and GPG key
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          git-commit-gpgsign: true
          git-committer-email: "${{ secrets.XLABS_CI_EMAIL }}"
          git-committer-name: "${{ secrets.XLABS_CI_NAME }}"
          git-push-gpgsign: true
          git-tag-gpgsign: true
          git-user-signingkey: true
          gpg-private-key: ${{ secrets.XLABS_CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.XLABS_CI_GPG_PASSPHRASE }}

      - name: Extract version from changelog
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 2
          path: ./CHANGELOG.md

      - uses: papeloto/action-zip@v1
        with:
          recursive: false
          files: build/bin/x64/Release/iw6x.exe
          dest: iw6x-${{ steps.changelog_reader.outputs.version }}.zip
      - name: Sign ZIP file
        run: gpg --output "iw6x-${{ steps.changelog_reader.outputs.version }}.zip.sig" --detach-sig "iw6x-${{ steps.changelog_reader.outputs.version }}.zip"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog_reader.outputs.version }}
          release_name: ${{ steps.changelog_reader.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}

      - name: Upload Release ZIP
        id: upload-release-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/iw6x-${{ steps.changelog_reader.outputs.version }}.zip
          asset_name: iw6x-${{ steps.changelog_reader.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload Release ZIP signature
        id: upload-release-zip-signature
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/iw6x-${{ steps.changelog_reader.outputs.version }}.zip.sig
          asset_name: iw6x-${{ steps.changelog_reader.outputs.version }}.zip.sig
          asset_content_type: text/plain

      - name: Create Pull Request to merge master back into develop
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete-branch: true
          branch: master
          body: |
            This Pull Request contains all changes done for the release of ${{ steps.changelog_reader.outputs.version }}, ready to be merged back into `master`.

            This release should be merged in due time to make sure that changes done to files such as the changelog as part of the release are also contained on the `develop` branch.
          title: Merge ${{ steps.changelog_reader.outputs.version }} into develop
